import type { LucideIcon } from 'lucide-react'
import {
  Anchor,
  Apple,
  Atom,
  Bandage,
  BatteryCharging,
  Bike,
  Bird,
  Bone,
  Book,
  BookOpen,
  Brain,
  Building,
  Building2,
  Bus,
  Calculator,
  Camera,
  Car,
  Carrot,
  Cat,
  Cloud,
  CloudRain,
  Coffee,
  Compass,
  Cpu,
  Database,
  Dna,
  Dog,
  Droplets,
  Dumbbell,
  Egg,
  Factory,
  Fish,
  FlaskConical,
  Flower2,
  Fuel,
  GraduationCap,
  Guitar,
  Hammer,
  Heart,
  HeartPulse,
  Home,
  IceCreamCone,
  Key,
  Laptop,
  Leaf,
  Lightbulb,
  Lock,
  MapPin,
  Medal,
  Mic,
  Microscope,
  Milk,
  Monitor,
  Moon,
  Mountain,
  Music,
  Palette,
  PawPrint,
  Pencil,
  PenTool,
  Pill,
  Pizza,
  Plane,
  Recycle,
  Rocket,
  Ruler,
  Scissors,
  ShieldCheck,
  Ship,
  Smartphone,
  Smile,
  Sprout,
  Star,
  Stethoscope,
  Sun,
  Syringe,
  Target,
  Tent,
  TestTube,
  Thermometer,
  Train,
  Trash2,
  TreeDeciduous,
  Trophy,
  Umbrella,
  Waves,
  Wheat,
  Wifi,
  Wind,
  Wrench,
  Zap,
} from 'lucide-react'

/** Un concepto del dominó: reemplaza al número de una mitad de ficha. */
export type DominoConcept = {
  conceptId: string
  label: string
  /** Clave del catálogo DOMINO_ICONS; se resuelve al componente de ícono al pintar. */
  icon: string
  /** Color hex con el que se pinta el ícono. */
  color: string
}

export type DominoConfig = {
  /** Fichas que recibe el jugador al repartir; el resto queda en el pozo. */
  handSize: number
}

export const DEFAULT_DOMINO_CONFIG: DominoConfig = { handSize: 7 }

export const MIN_DOMINO_CONCEPTS = 6
export const MAX_DOMINO_CONCEPTS = 10

/**
 * Catálogo de íconos que puede elegir quien crea un dominó. El contenido
 * guarda solo la clave (string), no el componente — así el juego sigue
 * siendo data pura en la base, y el cliente resuelve el dibujo. Cubre
 * categorías amplias (naturaleza, ciudad, tecnología, salud, alimentación,
 * transporte, arte, ciencia, deportes, animales, clima, objetos comunes)
 * para servir a cualquier materia, no solo temática ambiental.
 */
export const DOMINO_ICONS: Record<string, LucideIcon> = {
  // Genéricos / comunes (primero, para que emptyConcept() empiece por acá)
  star: Star,
  heart: Heart,
  smile: Smile,
  lightbulb: Lightbulb,
  key: Key,
  lock: Lock,
  target: Target,
  compass: Compass,
  mapPin: MapPin,
  trophy: Trophy,
  medal: Medal,
  // Naturaleza / ambiente
  sun: Sun,
  moon: Moon,
  leaf: Leaf,
  sprout: Sprout,
  tree: TreeDeciduous,
  flower: Flower2,
  mountain: Mountain,
  waves: Waves,
  droplets: Droplets,
  wind: Wind,
  cloud: Cloud,
  cloudRain: CloudRain,
  thermometer: Thermometer,
  recycle: Recycle,
  zap: Zap,
  batteryCharging: BatteryCharging,
  fuel: Fuel,
  // Animales
  fish: Fish,
  bird: Bird,
  cat: Cat,
  dog: Dog,
  pawPrint: PawPrint,
  bone: Bone,
  // Ciudad / transporte
  building: Building,
  building2: Building2,
  home: Home,
  car: Car,
  bus: Bus,
  bike: Bike,
  train: Train,
  plane: Plane,
  ship: Ship,
  rocket: Rocket,
  anchor: Anchor,
  tent: Tent,
  umbrella: Umbrella,
  factory: Factory,
  trash: Trash2,
  // Tecnología
  cpu: Cpu,
  laptop: Laptop,
  smartphone: Smartphone,
  wifi: Wifi,
  database: Database,
  monitor: Monitor,
  // Salud
  heartPulse: HeartPulse,
  pill: Pill,
  syringe: Syringe,
  bandage: Bandage,
  brain: Brain,
  stethoscope: Stethoscope,
  // Alimentación
  apple: Apple,
  carrot: Carrot,
  wheat: Wheat,
  egg: Egg,
  milk: Milk,
  coffee: Coffee,
  pizza: Pizza,
  iceCream: IceCreamCone,
  // Arte / música
  palette: Palette,
  music: Music,
  camera: Camera,
  mic: Mic,
  guitar: Guitar,
  // Ciencia / educación
  book: Book,
  bookOpen: BookOpen,
  graduationCap: GraduationCap,
  pencil: Pencil,
  penTool: PenTool,
  ruler: Ruler,
  calculator: Calculator,
  microscope: Microscope,
  testTube: TestTube,
  flaskConical: FlaskConical,
  atom: Atom,
  dna: Dna,
  // Deportes
  dumbbell: Dumbbell,
  // Objetos comunes / herramientas
  scissors: Scissors,
  hammer: Hammer,
  wrench: Wrench,
  shieldCheck: ShieldCheck,
}

/** Etiquetas en español para el selector de íconos del formulario. */
export const DOMINO_ICON_LABELS: Record<string, string> = {
  star: 'Estrella',
  heart: 'Corazón',
  smile: 'Sonrisa',
  lightbulb: 'Bombilla',
  key: 'Llave',
  lock: 'Candado',
  target: 'Objetivo',
  compass: 'Brújula',
  mapPin: 'Ubicación',
  trophy: 'Trofeo',
  medal: 'Medalla',
  sun: 'Sol',
  moon: 'Luna',
  leaf: 'Hoja',
  sprout: 'Brote',
  tree: 'Árbol',
  flower: 'Flor',
  mountain: 'Montaña',
  waves: 'Olas',
  droplets: 'Agua',
  wind: 'Viento',
  cloud: 'Nube',
  cloudRain: 'Lluvia',
  thermometer: 'Termómetro',
  recycle: 'Reciclaje',
  zap: 'Energía',
  batteryCharging: 'Batería',
  fuel: 'Combustible',
  fish: 'Pez',
  bird: 'Ave',
  cat: 'Gato',
  dog: 'Perro',
  pawPrint: 'Huella animal',
  bone: 'Hueso',
  building: 'Edificio',
  building2: 'Rascacielos',
  home: 'Casa',
  car: 'Carro',
  bus: 'Transporte',
  bike: 'Bicicleta',
  train: 'Tren',
  plane: 'Avión',
  ship: 'Barco',
  rocket: 'Cohete',
  anchor: 'Ancla',
  tent: 'Carpa',
  umbrella: 'Sombrilla',
  factory: 'Industria',
  trash: 'Residuos',
  cpu: 'Procesador',
  laptop: 'Portátil',
  smartphone: 'Celular',
  wifi: 'Wifi',
  database: 'Base de datos',
  monitor: 'Monitor',
  heartPulse: 'Pulso',
  pill: 'Pastilla',
  syringe: 'Jeringa',
  bandage: 'Curita',
  brain: 'Cerebro',
  stethoscope: 'Estetoscopio',
  apple: 'Manzana',
  carrot: 'Zanahoria',
  wheat: 'Trigo',
  egg: 'Huevo',
  milk: 'Leche',
  coffee: 'Café',
  pizza: 'Pizza',
  iceCream: 'Helado',
  palette: 'Paleta',
  music: 'Música',
  camera: 'Cámara',
  mic: 'Micrófono',
  guitar: 'Guitarra',
  book: 'Libro',
  bookOpen: 'Libro abierto',
  graduationCap: 'Graduación',
  pencil: 'Lápiz',
  penTool: 'Pluma',
  ruler: 'Regla',
  calculator: 'Calculadora',
  microscope: 'Microscopio',
  testTube: 'Tubo de ensayo',
  flaskConical: 'Matraz',
  atom: 'Átomo',
  dna: 'ADN',
  dumbbell: 'Pesas',
  scissors: 'Tijeras',
  hammer: 'Martillo',
  wrench: 'Llave inglesa',
  shieldCheck: 'Escudo',
}

export const DOMINO_ICON_KEYS = Object.keys(DOMINO_ICONS)

/** Ícono de respaldo cuando el contenido trae una clave que este cliente no conoce. */
export function iconForConcept(key: string): LucideIcon {
  return DOMINO_ICONS[key] ?? Leaf
}
